upstream storepailot {
    server store-pailot-ai-admin-nginx:80;
}

server {
    listen 80;
    server_name storepailotadmin.test;
    client_max_body_size 64M;

    location / {
        proxy_pass http://storepailot/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
    }
}
